version: '3.8'

services:
  prometheus:
    image: prom/prometheus
    container_name: prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--storage.tsdb.retention.time=15d'
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml:ro
      - ./prometheus-data:/prometheus
    ports:
      - "9090:9090"
    user: "65534:65534"  # Utilisateur non privilégié pour des raisons de sécurité
    restart: unless-stopped

  pushgateway:
    image: prom/pushgateway
    container_name: pushgateway
    ports:
      - "9091:9091"
    restart: unless-stopped

  grafana:
    image: grafana/grafana
    container_name: grafana
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_PATHS_PROVISIONING=/var/lib/grafana/provisioning
    volumes:
      - ./grafana:/var/lib/grafana

    depends_on:
      - prometheus
    ports:
      - "3000:3000"
    user: "472:472"
    restart: unless-stopped

  exporter:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: exporter
    command: ["python", "exporter.py"]
    depends_on:
      - pushgateway
    user: "0:0"  
    restart: no
