#fichier de configuration yaml pour prometheus pour aller chercher les metriques à un port precis 
global:
  scrape_interval: 10s

scrape_configs:

  - job_name: 'pushgateway'    #pour le push des métriques vers le pushgateway
    honor_labels: true
    static_configs:
      - targets: ['pushgateway:9091']

  - job_name: 'prometheus'
    static_configs:
      - targets: ['prometheus:9090']