name: CI/CD Feedback Analysis

on:
  push:
    branches:
      - main
      - ci-cd-tests
  pull_request:
    branches:
      - main
      - ci-cd-tests
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.11'] # Standardiser sur une version

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          # Installer les dépendances de test, y compris airflow pour les tests de DAG
          pip install pytest pytest-cov pytest-mock apache-airflow

      - name: Run Unit Tests & Generate Coverage
        env:
          # On s'assure que les tests qui dépendent de secrets sont sautés
          # s'ils ne sont pas explicitement marqués comme intégration
          PYTEST_RUNNING: "true"
        run: |
          python -m pytest -v --cov=api --cov=scripts_data --cov-report=xml -m "not integration"

      - name: Upload Coverage Report
        uses: actions/upload-artifact@v4
        with:
          name: coverage-report
          path: coverage.xml

      - name: Set up GCP Credentials
        if: github.ref == 'refs/heads/main'
        run: |
          echo "${{ secrets.GCP_CREDENTIALS_JSON }}" > gcp_credentials.json
          chmod 600 gcp_credentials.json # Set appropriate permissions
        env:
          GCP_CREDENTIALS_JSON: ${{ secrets.GCP_CREDENTIALS_JSON }}

      - name: Run Integration Tests (on main branch only)
        if: github.ref == 'refs/heads/main'
        env:
          ANTHROPIC_API_KEY: ${{ secrets.ANTHROPIC_API_KEY }}
          PROJECT_ID: ${{ secrets.PROJECT_ID }}
          PYTEST_RUNNING: "true"
          GOOGLE_APPLICATION_CREDENTIALS: gcp_credentials.json # Point to the created file
        run: |
          python -m pytest -v -m "integration"